### PR TITLE
Issue #1187 - Refresh context for all instances by actuator/bus-refresh

### PR DESCRIPTION
**Pull request by skosijer**

### CODE REVIEW

**Comment by joshiste** [comment]
Could you resolve those merge conflicts?

**Comment by skosijer** [comment]
I will create another PR with only one commit and resolve the conflicts. I don't need issue #1200 here.

**Comment by skosijer** [comment]
@joshiste Fixed it.

**Comment by joshiste** [comment]
@skosijer did you read my last comment? Are you willing to update the PR?

**Comment by Riggs333** [comment]
@skosijer Are you still working on that issue?

**Pull request closed without merging**
