### PR TITLE
Multiple end points

### PR DESCRIPTION
**Pull request by mikexliu**

### CODE REVIEW

**Comment by mikexliu** [comment]
I couldn't think of a case where we would only want to register against exactly one admin-server if there are multiple available. My use case is we have a centralized admin-server but each service also is hosting its own admin-server. I would like to have the data be pushed to both endpoints.

If the centralized admin-server goes down, it's still accessible via the service itself (or if you have multiple dedicated admin-servers, then they would have the data immediately as opposed to having to wait for the next registration).

**Comment by joshiste** [comment]
First of all thank you for the PR.

In my opinion an option `spring.boot.admin.register-once`. With default for the old behaviour would be good. And I would appreciate if you would sqash all commits into a single one and do a forced push to your branch.

**Comment by mikexliu** [comment]
@joshiste 
Thanks. I've squashed it into one commit. The only issue I still have is the return value of register. If you are registering against multiple and some fail, should it still be false or should it be true? Current implementation is true if even one is successful.

**Comment by joshiste** [comment]
merged with b0330cda6e8c61450c8dbeec91d1e56361c9f5a5

**Pull request closed without merging**
