### PR TITLE
Add mappings page

### PR DESCRIPTION
**Pull request by bas-jan**
Added a simple page showing the results of `actuator/mappings` with a search bar.

### CODE REVIEW

**Comment by joshiste** [comment]
Master has now switched to 2.x so you need to update this PR...
... and since the UI has become a complete make over this means a bit more work ...

**Comment by bas-jan** [comment]
Thank you. I am reworking the code.
The new UI looks like a nice improvement.

**Comment by joshiste** [comment]
So will you rework the code for 2.x?

**Comment by bas-jan** [comment]
Yes, I will do this. I started to rework the code, but the structure of the Angular-code of 2.x was still changing a lot, so I decided to wait a bit for it to stabalize.
Thanks.

**Comment by joshiste** [comment]
closed due to missing feedback

**Pull request closed without merging**
