### PR TITLE
Add Korean translation 

### PR DESCRIPTION
**Pull request by kurly09**
Add Korean support

### CODE REVIEW

**Comment by kurly09** [comment]
Well I added Korean json files only.
What Is the next move that I merge my branch?

**Comment by joshiste** [comment]
The translation for the following file(s) is missing:

```
shell/i18n.en.json
```

**Comment by kurly09** [comment]
@joshiste TYVM
I added missed file.

**Comment by joshiste** [comment]
Merged with aeec5161af6c8fb8e23a7221d95cc52b3dfb1bd2

**Comment by joshiste** [comment]
@kurly09 just spotted that the `src/main/frontend/views/instances/loggers/i18n.ko.json` has the wrong translations. Could you please submit a second PR fixing the translations?

**Pull request closed without merging**
