### PR TITLE
WIP Spring Boot 2.0.0.M1

### LINKED ISSUE #465: Support for Spring Boot 2.0.0
Spring Boot 2.0.0 is going to be released soon.

See PR #466

### PR DESCRIPTION
**Pull request by micheljung**
First steps to support Spring Boot 2.0.0, based on Spring Boot 2.0.0.M1.

Some tests still fail, feel free to pick it up.

Fixes #465

### CODE REVIEW

**Comment by joshiste** [comment]
Since this PR is only half of the work I close it in favor of the issue #465

**Comment by micheljung** [comment]
This PR is half of the work required to solve #465. What's the point of closing this PR?

**Comment by joshiste** [comment]
First of all your work isn't lost... since you got yourself a branch you can work on. 

My personal opinion: a PR says 'look what i've (nearly) finished - here is my code - do you want to integrate it in your project after revising ?'.
But this PR is far away from being done and has more the notion of 'Look here - wouldn't be this a nice thing to do? Should we work on it?' That's what issues are....
If you want to invite others to work with you on your branch you can tell them in the issue...

Additionally to that I already have a branch to work on 2.x and this PR is not even half the work...
It just fixes the compile issues but leaves things out as:
 - Spring Cloud for Spring Boot 2.x (afaik they not started the work yet)
 - Support reactive (non servlet) web-applications (by now the actuator doesn't work for reactive apps). 
- Changes in the Actuator endpoints

**Comment by Tlsy** [comment]
When to support spring-boot 2.x version ，
I can not wait.......

**Comment by jmirc** [comment]
Do you have any timeline to support spring boot 2.0

**Comment by joshiste** [comment]
As I'm working on my free time for that I can't give you any timeline. I've currently have a local branch for 2.0 which I'll merge into master, when boot 2.0.0.RC1 is out.

**Comment by jmirc** [comment]
Do you need help? If you make this branch available, I would be able to help you on my free time too

**Comment by aantono** [comment]
It would be great if you could share a branch.  I'm working on an update of a Spring Boot Cookbook, where I've provided examples of how to integrate SBA, to SB 2.0, and would love to be able to test the integration and hopefully provide some feedback.

**Pull request closed without merging**
