### PR TITLE
Client add Spring InetUtils function

### PR DESCRIPTION
**Pull request by zhaolin81**
add findFirstNonLoopbackAddress() instead of InetAddress.getLocalHost()

support application.yml/application.properties

# List of Java regex expressions for network interfaces that will be ignored.
ignoredInterfaces: 
  - eth1

# List of Java regex expressions for network addresses that will be preferred.
preferredNetworks: 
  - 10.*
  - 192.168.*

### CODE REVIEW

**Comment by joshiste** [comment]
What problem are you trying to solve?

**Comment by zhaolin81** [comment]
hello,I got 127.0.0.1 when i call InetAddress.getLocalHost() on my centos7 with multi-network interfaces

**Comment by joshiste** [comment]
If you set `server.address` for your application the SBA client will use this address.

**Comment by zhaolin81** [comment]
> If you set `server.address` for your application the SBA client will use this address.

i know that，but there is a problem when use config server，more than one client instances shared one config using ctrip apollo. server.address not support regex.

**Comment by joshiste** [comment]
> there is a problem when use config server，more than one client instances shared one config using ctrip apollo. server.address not support regex.

@zhaolin81 in my personal opinion this should be solved using envorinmonent/host dependent config.

I'm currently not very keen on merging the copied code from the spring cloud project. You're the first one in 4 years requesting this feature and currenty I don't want to add the additional complexity.
For now please solve the problem for yourself by subclassing the  `DefaultApplicationFacotry`.

**Comment by zhaolin81** [comment]
> > there is a problem when use config server，more than one client instances shared one config using ctrip apollo. server.address not support regex.
> 
> @zhaolin81 in my personal opinion this should be solved using envorinmonent/host dependent config.
> 
> I'm currently not very keen on merging the copied code from the spring cloud project. You're the first one in four years requesting this feature and currenty I don't want to add the extra complexity.
> For now please solve the problem for yourself by subclassing the `DefaultApplicationFacotry`.

ok,thanks alot.

**Pull request closed without merging**
