### PR TITLE
Support regular expressions for ignored services

### PR DESCRIPTION
**Pull request by ezraroi**
…iscovery.ignored-services

---
This change is [Reviewable](https://reviewable.io/reviews/codecentric/spring-boot-admin/379)

### CODE REVIEW

**Comment by ezraroi** [comment]
spring.boot.admin.discovery.ignored-service now supports regular expressions and not only service names

**Comment by ezraroi** [comment]
#377

**Comment by joshiste** [comment]
Hmm... I just digged into spring-cloud-netflix zuul's semantics of ignored services and they do a simple matching using `org.springframework.util.PatternMatchUtils#simpleMatch()`.
Do we need full blown regexes or should we align with 'em?

**Comment by ezraroi** [comment]
Cool,  i agree.  I will change

**Comment by joshiste** [comment]
Merged with some slight modifications (removed guava, changed docs).

**Pull request closed without merging**
