### PR TITLE
#1174 - Custom interceptors for http requests made by the UI

### LINKED ISSUE #1174: Custom interceptors for http requests made by the UI
We need to make a login call to a auth service from the client and store the JWT token in the client and add it to every request made by the client code.

The auth service is doing kerberos auth so it is not possible to do it in the server side.
In version 1 of boot admin we added angular interceptor to do this, is it possible to do it also in version 2?

### PR DESCRIPTION
**Pull request by ezraroi**
fixes #1174

---
This change is [Reviewable](https://reviewable.io/reviews/codecentric/spring-boot-admin/1178)

### CODE REVIEW

**Comment by joshiste** [comment]
could you add a sample to the docs?

**Comment by joshiste** [comment]
Did you check that this works for you?

**Comment by ezraroi** [comment]
Yes,checked locally. Will update the docs

**Comment by ezraroi** [comment]
@joshiste Added information to the docs also

**Pull request merged**
