### PR TITLE
Support configuring VueJS router options

### PR DESCRIPTION
**Pull request by asibross**
This PR allows users to configure the VueJS router options as defined [here](https://router.vuejs.org/api/#router-construction-options).

This is related to #876, as it enables setting history mode.

### CODE REVIEW

**Comment by asibross** [comment]
Going with this approach for all users will mean that all html calls will not be served if they fall under the context-path. As the default is /, it means:
1. Actuator endpoints.
2. /login
3. Any other endpoints the user may wish to serve along side the admin server.

While the first two could be explicitly allowed, the third may be an issue.

**Comment by joshiste** [comment]
> Going with this approach for all users will mean that all html calls will not be served if they fall under the context-path. As the default is /, it means: ...

You're correct therefore the foeward to the index should only happen if no other handler has matched and the `Accept`-Header contains `application/html`

**Comment by joshiste** [comment]
> ...as all browsers send '*/*' in their accept headers.
 
Thats not quire correct: 
Safari: `Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8`
Chrome: `Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8`

> This is also not bullet proof, since the instances/applications ... endpoints which return json will still take precedence...

Hmm I guess we need still to figure out, how we can properly support this properly without the burden of too compley configuration options and without breaking things...

**Comment by asibross** [comment]
Please checkout my latest commit for how to support this in MVC. For WebFlux, I don't have much experience with, I tried doing that with a WebFilter but I can't apply it to the AdminControllerHandlerMapping only.

**Comment by joshiste** [comment]
I changed the base to `master`. I don't want this kind of risky change in the `2.0.x` branch.

**Comment by asibross** [comment]
Hey @joshiste, I updated the PR to resolve conflicts.
Do you have any suggestion on how to handle this in WebFlux based apps?
I can make this configurable so that only MVC apps will have the history mode on.

**Comment by asibross** [comment]
Hey @joshiste, did you get a chance to look over this PR?
As a middle ground, if you are not aware of any solution for the Reactive flavor, I can make this configurable with a property like: `spring.boot.admin.ui.history-mode-for-mvc=true` or some other property name.

**Pull request closed without merging**
