### PR TITLE
Fixes for Coveralls - #45

### LINKED ISSUE #45: Configure build for coveralls.io
I have activated coveralls.io for this repository: https://coveralls.io/r/codecentric/spring-boot-admin

Now the build needs to be configured, so that it reports coverage data to coveralls. More information can be found here: https://github.com/trautonen/coveralls-maven-plugin

An example configuration is here: https://github.com/trautonen/jersey-mustache

### PR DESCRIPTION
**Pull request by dgomesbr**
* House keeping to get all the ignored files correctly for eclipse, ide…
* Adding the report for jacoco
* Housekeeping with version properties
* Adding Jacoco dependencies (like jersey-mustache)
* Coveralls-maven configured
* Fix #45

### CODE REVIEW

**Comment by britter** [comment]
Hello @dgomesbr,

let's try to keep things simple and don't mix up stuff here. 

The changes to .gitignore are unrelated to the issue (which is about adding coveralls support). We should leave this change out and create a separate issue for it. My personal opinion about this is, to add nothing to .gitignore that is specific to a dev environment (for example .settings). This stuff belongs in your global gitignore file. The only thing that should be in .gitignore are temp files generated by your build tools, like the target folder generated by maven or sample files for the build like build.properties.sample.
I would also like to see a separate PR for the house keeping in pom.xml.
Splitting things up makes it easier to review stuff and creates a clearer git history.

May I ask you to modify your PR?

best regards,
Benedikt

**Comment by dgomesbr** [comment]
Thanks for the feedback, could reject both of changes? I'll backport for 3-4 PR for each modification.

**Comment by britter** [comment]
Very nice, looks like your changes work! :+1: 

I don't understand what you mean by "could reject both of changes".

**Comment by dgomesbr** [comment]
I didn't know as well that I could close my own PR. *sigh* I'm creating all
branches necessary and/or the issues related to housekeeping.



Att,

Diego Magalhães

*http://diegomagalhaes.com <http://diegomagalhaes.com>claro @ +55 21 99411
2823*

**Pull request closed without merging**
