### PR TITLE
WIP: add filter to dashboard

### LINKED ISSUE #1396: Add filters to Wallboard
We have 6 monitored services installed on 10 environnements.  So our wallboard became unreadable.
I suggest, to enhance the UI in order to permit to the users to filter by environnment, service and status.

### PR DESCRIPTION
**Pull request by Glosur**
* filter is reflected in queryparams

Closed #1396

image
image

I definitely agree that the UI could be better and would be happy to improve it given some feedback
Here's what I think:
* The transparent background allow for instant feedback on the filter and is nice
* It would be nice to have an indication if a filter is active (maybe the nulber of instances filtered out)
* I also think any text is kind of removing some of the 'cleanliness' of the wallboard

@joshiste What do you think ?

### CODE REVIEW

**Comment by joshiste** [comment]
I'd favor having the input appear above the hexagons and not as overlay.

The filter button could have an active/inactive state and some kind of "2 of 10 shown" label.

**Comment by Glosur** [comment]
New UI looks like :
No filter: 
image
Filter with input visible:
image
Filter without input:
image

**Comment by joshiste** [comment]
Hmm the black text on dark gray background is very hard to read...

**Comment by joshiste** [comment]
> Hmm the black text on dark gray background is very hard to read...

@Glosur Are you going to update the PR to improve the readibility?

**Comment by Glosur** [comment]
Yeah, I'll give it another shot this weekend

**Comment by Glosur** [comment]
@joshiste Tried to do some stuff but didnt manage to have any satisfying results :/

**Comment by Riggs333** [comment]
@Glosur Are you still working on this? Otherwise we would like to close this.

**Comment by Glosur** [comment]
I'm not woking on this anymore, sorry I didn't find the time to polish the contribution

**Pull request closed without merging**
