### PR TITLE
Issue #1342 - calculate UiExtension.resourcePath relative to AdminServerUiProperties.resourceLocations

### PR DESCRIPTION
**Pull request by bratwurzt**

### CODE REVIEW

**Comment by joshiste** [comment]
Thanks for this PR. Could you pleas elaborate a bit on why you made this changes?

Imho it looks like working around the spring security config...
I wonder wether adding the extensions path's to the config would be enough?

```
authorizeRequests.antMatchers(this.adminServer.path("/assets/**"), this.adminServer.path("/my-extension/**")).permitAll()
```

Also this change breaks the settings for all people which put there extensions into `/META-INF/spring-boot-admin-server-ui/extensions/{name}/`

**Comment by bratwurzt** [comment]
> 
> 
> Thanks for this PR. Could you pleas elaborate a bit on why you made this changes?
> 
> Imho it looks like working around the spring security config...
> I wonder wether adding the extensions path's to the config would be enough?
> 
> ```
> authorizeRequests.antMatchers(this.adminServer.path("/assets/**"), this.adminServer.path("/my-extension/**")).permitAll()
> ```
No, this does not work. Like @mbwhelan commented in https://github.com/codecentric/spring-boot-admin/issues/1342#issuecomment-620529694, this has been caused by Spring Security enabling default security headers. But even if I disable them like 
```
http.headers().contentTypeOptions().disable()
```
it still does not work.
> Also this change breaks the settings for all people which put their extensions into `/META-INF/spring-boot-admin-server-ui/extensions/{name}/`

Yes, this is sadly true. But IMO extensions are assets anyway. :)

**Comment by bratwurzt** [comment]
Ok, I reverted move to assets folder - all this does now is calculate `de.codecentric.boot.admin.server.ui.extensions.UiExtension#resourcePath` relative to `de.codecentric.boot.admin.server.ui.config.AdminServerUiProperties#resourceLocations`

**Comment by bratwurzt** [comment]
@joshiste some tests are failing which I haven't touched. I cannot trigger rebuild, could you?

**Comment by joshiste** [comment]
Could you add an (integration) tests that reproduces the error from the github issue to prevent this from happening again?

**Comment by joshiste** [comment]
@bratwurzt there is still some failing tests:

 ```
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.044 s <<< FAILURE! - in de.codecentric.boot.admin.server.ui.extensions.UiExtensionsScannerTest
[ERROR] should_not_find_extensions  Time elapsed: 0.021 s  <<< FAILURE!
java.lang.AssertionError: 
Expecting empty but was:<[UiExtension(resourcePath=custom/custom.abcdef.js, resourceLocation=classpath:/META-INF/spring-boot-admin-server-ui/extensions/custom/custom.abcdef.js),
    UiExtension(resourcePath=custom/custom.abcdef.css, resourceLocation=classpath:/META-INF/spring-boot-admin-server-ui/extensions/custom/custom.abcdef.css)]>
	at de.codecentric.boot.admin.server.ui.extensions.UiExtensionsScannerTest.should_not_find_extensions(UiExtensionsScannerTest.java:53)
```

**Comment by mbwhelan** [comment]
@bratwurzt Thanks for doing this.  How does this change make the mime type work with the nosniff header?

**Comment by bratwurzt** [comment]
> 
> 
> @bratwurzt Thanks for doing this. How does this change make the mime type work with the nosniff header?

Honestly, I don't know. All I did is set base resource location the same as if a script/stylesheet is located in assets folder.

**Comment by joshiste** [comment]
@bratwurzt I've looked into this PR and figured why it works:

in the end you are serving the extensions files on a different path which isn't recognized by the `HomepageForwardingFilter` as false positive.

The HomepageForwardingFilter is needed in order to make the vue router history mode work and redirects certain requests to the index.html. 

I've done a similiar fix in https://github.com/codecentric/spring-boot-admin/commit/18e295bdb6983e1a6b8817f84457c60b9b357a47 for serving the extensions assets on a different path but without the overhead of the relative path computation - therefore I'm closing this PR.

Nevertheless thank you for your PR!
Even it didn't make it into master it pointed me to the correct solution.

**Comment by bratwurzt** [comment]
> 
> 
> @bratwurzt I've looked into this PR and figured why it works:
> 
> in the end you are serving the extensions files on a different path which isn't recognized by the `HomepageForwardingFilter` as false positive.
> 
> The HomepageForwardingFilter is needed in order to make the vue router history mode work and redirects certain requests to the index.html.
> 
> I've done a similiar fix in [18e295b](https://github.com/codecentric/spring-boot-admin/commit/18e295bdb6983e1a6b8817f84457c60b9b357a47) for serving the extensions assets on a different path but without the overhead of the relative path computation - therefore I'm closing this PR.
> 
> Nevertheless thank you for your PR!
> Even it didn't make it into master it pointed me to the correct solution.

Hey @joshiste, sorry to ping you on a closed issue but I found that with `spring.boot.admin.context-path` set this throws 404. 

I think it's because in index.html calculated paths for extensions are absolute instead of relative (prepended slash before "extensions" string).

**Comment by joshiste** [comment]
@bratwurzt this has already been fixed with https://github.com/codecentric/spring-boot-admin/issues/1426

**Pull request closed without merging**
