### PR TITLE
Customizable header elements (label and logo)

### PR DESCRIPTION
**Pull request by dickerpulli**

### CODE REVIEW

**Comment by dickerpulli** [comment]
Implementing request https://github.com/codecentric/spring-boot-admin/issues/212

**Comment by dickerpulli** [comment]
Implements https://github.com/codecentric/spring-boot-admin/issues/212

**Comment by joshiste** [comment]
@dickerpulli I'm currently reviewing this and despite the fact that I suggested this solution I'm currently a bit skeptical on this....

**Comment by joshiste** [comment]
merged with 6676a14a51b813c4a37c2386a7cd7e9fa8d43061

**Comment by anandvarkeyphilips** [comment]
Is it available in 2.0.1 ??
 Image(404 Error) is not working for me.. Heading is being changed..

**Comment by dickerpulli** [comment]
Yes, it is available and works. I used to set the property like this.
``spring.boot.admin.ui.brand=<span>Spring Boot Admin - ${environment}</span>``

**Comment by anandvarkeyphilips** [comment]
@dickerpulli , so where do you place your svg file?? I guess thats my problem.

**Comment by dickerpulli** [comment]
In my case the file is placed in **src/main/resources/assets/img/icon-spring-boot-admin.svg**

But I have also configured a new ResourceHandler to deliver the image.

```java
@Configuration
public class ResourcesConfig implements WebMvcConfigurer {

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("/assets/**").addResourceLocations("classpath:/assets/");
    }

}
```

**Comment by dickerpulli** [comment]
So, you have to do two steps

1. Add property **spring.boot.admin.ui.brand=**
2. Add ResourceHandler to deliver the image 
```java
@Configuration
public class ResourcesConfig implements WebMvcConfigurer {

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("/custom/path/to/**").addResourceLocations("classpath:/another/custom/path/in/classpath/to/");
    }

}
```

**Comment by dickerpulli** [comment]
I will document it in the Quick Guide

**Comment by joshiste** [comment]
Or you can place it in `META-INF/spring-boot-admin-server-ui` - SBA registers a resource handler for that location.

**Pull request closed without merging**
