### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ozkanpakdil**
took me a while to figure out those slashes :)

### CODE REVIEW

**Comment by ozkanpakdil** [comment]
btw while testing I had issues with js and css load. is there a way to fix that one ?
image

**Comment by joshiste** [comment]
which platform are you running on? I don't need those.
and regarding the css: did you tried to use the spring-boot-admin-sample-servlet with `spring.profiles.active=dev` ?

**Comment by ozkanpakdil** [comment]
I am using win10 and spring-boot-admin-sample-war. I added these to application.yml
`spring.boot.admin.ui.title: Project name - Spring boot admin

spring.boot.admin.ui.cache.no-cache: true
spring.boot.admin.ui.resource-locations: file:@project.basedir@/../../spring-boot-admin-server-ui/target/dist/
spring.boot.admin.ui.template-location: file:@project.basedir@/../../spring-boot-admin-server-ui/target/dist/
spring.boot.admin.ui.cache-templates: false
`
if I have the slashes I got this
image

also I find those slashes are not needed from spring-boot-admin-sample-servlet there yml is 
`spring:
  profiles: dev
  boot:
    admin:
      ui:
        cache:
          no-cache: true
        template-location: file:@project.basedir@/../../spring-boot-admin-server-ui/target/dist/
        resource-locations: file:@project.basedir@/../../spring-boot-admin-server-ui/target/dist/
        cache-templates: false
        extension-resource-locations: file:@project.basedir@/../spring-boot-admin-sample-custom-ui/target/dist/
`

**Comment by ozkanpakdil** [comment]
about profiles there is something wrong with it. thats why I used the other sample. normally when I give -Pdev that should be active but somehow I could not activate dev profile from command line. tried
`mvn spring-boot:run -Dspring.profiles.active=dev -Pdev`
anyway finally I changed the yml and make active like this
image
and the result is
image
just FYI

**Comment by joshiste** [comment]
Ok adding the slashes also works on OSX. But to merge this PR we should align the `spring-boot-admin-sample-servlet/src/main/resources/application.yml`. Could you update this PR?

**Comment by ozkanpakdil** [comment]
hmm I think we have a miscommunication. I am trying to remove those slashes from the document. which is already removed in spring-boot-admin-sample-servlet/src/main/resources/application.yml. 

or am I missing something ?

**Comment by joshiste** [comment]
oh, you're right.

**Pull request merged**
