### PR TITLE
Fixes #156: Add a spring.boot.admin.client.enabled property to contro…

### LINKED ISSUE #156: Add a spring.boot.admin.client.enabled property to control if the client is enabled or disabled
A `spring.boot.admin.client.enabled` property would still be nice and more intuitive than leaving spring.boot.admin.url empty.

Change 
`@ConditionalOnProperty("spring.boot.admin.url")` to
```
@ConditionalOnProperty(
        prefix = "spring.boot.admin.client",
        name = {"enabled"},
        matchIfMissing = true
)
```
The client would be enabled by default. But it would break backward compability. 
Or do you want me to write a more complex SpringBootClientEnablerCondition which extends SpringBootCondition and checks both properties?

### PR DESCRIPTION
**Pull request by RobWin**
…l if the client is enabled or disabled

### CODE REVIEW

**Comment by RobWin** [comment]
I fix the tests on monday.

**Comment by RobWin** [comment]
If this PR is ok for you, I would update the documentation.

**Comment by joshiste** [comment]
Looks good to me. The metadata is completely generated for the client. And since you added the property to the configurationproperties there is no need for handcrafted metadata...
Please use the eclipse-formatter rules from the repo-root.
Could you also squash your changes to a single commit after adding the docs?

**Comment by RobWin** [comment]
Yes I can squash them. Can I use the eclipse-formatter with IntelliJ as well?

**Comment by joshiste** [comment]
I think so, have a look at https://plugins.jetbrains.com/plugin/6546

**Comment by RobWin** [comment]
I have squashed the commits and updated the documentation.

**Comment by joshiste** [comment]
Merged with 45a19cd40df316b0103b4c2d5943821444c7074e

I did some small changes: 
* Removed the enabled from AdminClientProperties since it was used nowhere else.
* Renamed the condition to SpringBootAdminClientEnabledCondition
* Support for relaxed bindings in the condition 

I also felt free to change your email-adress to the one used on github.

**Comment by RobWin** [comment]
Thx.
Does it generate the config meta data for the enabled property then, if it is removed?

**Comment by joshiste** [comment]
the one used in your previous PR...

**Pull request closed without merging**
