### PR TITLE
Configure VueJS with history mode

### PR DESCRIPTION
**Pull request by asibross**
This PR follows the instructions outlined [here](https://router.vuejs.org/guide/essentials/history-mode.html) to configure history mode.
It adds filters (both for servlet and webflux) to forward requests to the homepage.

This change will enable deep linking with OAuth2 which addresses #876.
This is a replacement for PR #896.

### CODE REVIEW

**Comment by joshiste** [comment]
Could you add a test to `AbstractAdminApplicationTest` that tests the behavior?

**Comment by joshiste** [comment]
Also the handler should be narrowed down to the content type `text/html,application/xhtml+xml` for the accept type.

**Comment by asibross** [comment]
Hey @joshiste, I added the requested tests and narrowed the content type.

**Comment by asibross** [comment]
Hey @joshiste, was wondering if you got a chance to see my latests changes to this PR which addresses your comments.
It would be nice to have this merged before a new release, currently at Netflix we just use a fork which only has this change.

**Comment by joshiste** [comment]
Yeah. I did but after thinking back and forth I‘m not sure about the approach. Currently I tend to make the mvc aware of the frontend routes as it involves less guessing and magic but adds some extra burden for custom extensions...

**Comment by asibross** [comment]
Hey @joshiste,
I understand your concerns and appreciate your feedback.
As a middle ground, can we make the VueRouter mode configurable? this will allow me to add the Filters on my side without introducing this change to everyone?

**Comment by joshiste** [comment]
>  this will allow me to add the Filters on my side without introducing this change to everyone?

I'm currently plan to to a proper solution with the upcoming 2.2.x (probably mid Jul, short after boot 2.x)

**Comment by asibross** [comment]
Cool. Thanks for the update.

**Comment by joshiste** [comment]
Thanks for your PR. I took a lot inspiration and also some code from it, creating a solution which shouldn't introduce any regression for existing routes.

superseded by https://github.com/codecentric/spring-boot-admin/pull/1127

**Pull request closed without merging**
