### PR TITLE
Change language label from region to language

### PR DESCRIPTION
**Pull request by ettingshausen**
Snipaste_2021-12-10_15-00-52

### CODE REVIEW

**Comment by SteKoe** [comment]
Hi @ettingshausen, 

thanks for your PR! We have fixed the tests and refactored your code a little bit. Please have a look.
[fixing_tests.patch.txt](https://github.com/codecentric/spring-boot-admin/files/7733829/fixing_tests.patch.txt)

In addition, we wonder what the correct output should look like. When removing the if statement you added, we get the same visual representation as shown in **your** screenshot. When we apply your PR, we get a slightly different result. 

### Using your code, we get the following result:
having-if-statement

### Without if statement, the result looks like this:
without-if-statement

**Comment by ettingshausen** [comment]
>In addition, we wonder what the correct output should look like. When removing the if statement you added, we get the same visual representation as shown in your screenshot. 

Nope, It's not the same. The last two label in my screenshot:
```
中文（简体）
中文（繁體）
```
And the one remove if statement: 
```
中文（中国）
中文（台湾）
```

**Comment by erikpetzold** [comment]
@ettingshausen 

But *with the if* we get the result from the screenshot above, so no brackets at all and different order.
*Without if* seems similar to your without if.

So we have different output than you. And additionally we do not understand what the if is needed for/what is correct.

**Comment by ettingshausen** [comment]
>So we have different output than you. And additionally we do not understand what the if is needed for/what is correct.

I noticed that.  The screenshot I pasted above was taken in Edge Browser(version 96.0.1054.57). I will check the other version later.

When I use Safari (version 15.2 (16612.3.6.1.8, 16612)) or Chrome (version 96.0.4664.110), I get the same output with yours above.
safari


> And additionally we do not understand what the if is needed for/what is correct.


```javascript
// Chinese
if (locale.toLowerCase().startsWith('zh')) {
     // Chinese simplified
     if (locale.endsWith('CN')) {
            langTag = '-Hans'
      }
     // Chinese traditional
      if (locale.endsWith('TW')) {
            langTag = '-Hant'
     }
}
```
The if statement above it looks not elegant enough. The purpose of using it is to correctly handle the display of Chinese language label.

Chinese has two standard,  Chinese simplified and Chinese traditional. Chinese simplified is the most widely used in the world, but Chinese traditional still used in many areas like Hong Kong, Taiwan etc.
> https://en.wikipedia.org/wiki/Chinese_characters

If we remove the if statement, it will render like this (Chrome):
```
中文（中国）
中文（台灣）
```
It looks like: 
```
Chinese（China）// used not only China
Chinese（Taiwan）// used not only Taiwan
```

With the if statement it will render like this (Chrome):
```
中文（中国）
中文（台灣）
```
It means

```
Chinese simplified
Chinese traditional
```

I think the last one is better.

**Pull request closed without merging**
