### PR TITLE
Add support for clearing caches.

### LINKED ISSUE #832: Boot 2.1.x: Support for clearing caches via `/caches` endpoint

### PR DESCRIPTION
**Pull request by semeiser**
closes #832

### CODE REVIEW

**Comment by joshiste** [comment]
As this targets 2.1.0 and I'm currently very busy you need to be a little patient.

**Comment by semeiser** [comment]
Sure, no rush! Thanks for the update. I'll try to keep the PR up-to-date/conflict-free.

**Comment by joshiste** [comment]
Hmm you implemented (similar to the loggers) that not all caches will be rendered at once. Do you expect the user to have hundreds (or thousands) of caches or can we remove this complexity?

**Comment by semeiser** [comment]
I do have an application with ~300 Caches, which makes for quite a long list :) But i think we can remove the lazy rendering and add it later if the need arises, i'll update the PR.

**Comment by joshiste** [comment]
No need to update - I'm already on it.

**Comment by joshiste** [comment]
merged with f68db90689391a586de19f8fdc9f71a58fa3e6b8 and polished in 6acbf1902537ba57acee4a895892cf21847e5bf2

**Comment by joshiste** [comment]
As a follow up we could now move the cache-related metrics to the caches view...

**Pull request closed without merging**
