### PR TITLE
Enable auto registration only for web environments

### PR DESCRIPTION
**Pull request by shashidarp**
Fixes issue https://github.com/codecentric/spring-boot-admin/issues/578

### CODE REVIEW

**Comment by joshiste** [comment]
Why you would even include the starter in non-web-applications???

**Comment by shashidarp** [comment]
Will do.

**Comment by shashidarp** [comment]
@joshiste Added a test for non web environment.

**Comment by joshiste** [comment]
merged with 8143743d9ef985fb10b3fcb7635bc869bb514610. Thx for contributing!

**Pull request closed without merging**
