### PR TITLE
Add support for Activiti spring boot starter endpoint

### PR DESCRIPTION
**Pull request by teggr**
Activiti spring boot starter exposes the /activiti endpoint which i've exposed through the admin ui. See
https://spring.io/blog/2015/03/08/getting-started-with-activiti-and-spring-boot for further details on creating a client. The Activiti entry will be shown even if not supported as its not totally clear how to filter the "apps" based on availability, like you can with the logging drop down menu

### CODE REVIEW

**Comment by joshiste** [comment]
Cool. Can you show some little screenshot?
I wonder if there is a neat way to make the ui extensible with modules/plugins so this could be an extra dependency? But for now I think we can add this to sba until there is a modular approach...

**Comment by teggr** [comment]
Hi,
I've attached a screenshot showing the activiti output. It will be empty if the spring boot app does not expose that endpoint.
activiti
I would hide the "Activti" link in the header, but the application object in scope in "apps.html" does not have the same properties, as those used in the drop-down list.
Ideally, yes, being able to support a modular approach would be ideal for extensions such as this. I'm just re-acquainting myself with angular, so if i have any thoughts on that I'll let you know. It's likely that I might want to build out a couple of extra parts, that are specific for my company applications.
I thought that I'd contribute this back as it has been documented on the spring blog, so it may be that there are others who would benefit from the feature.
Keep up the good work.
Cheers,
Robin

**Comment by teggr** [comment]
sorry, didn't mean to close with that comment

**Comment by joshiste** [comment]
Merged. 
Small changes: Activiti-section only appears when the endpoint is availible.

Thanks for Contribution!

**Pull request closed without merging**
