### PR TITLE
If tags exists in the Metatdata display them in the instance header

### PR DESCRIPTION
**Pull request by asibross**
#855

### CODE REVIEW

**Comment by joshiste** [comment]
I think it would be also good to have the tags as columns in the instances table for the "Applications" view.
Also I think it would be nice to have the tags explicitly in the backend model. We'd need to extract the tags in a similar fashion like we do for the version.

**Comment by asibross** [comment]
@joshiste, I updated the PR with above suggestions.

**Comment by joshiste** [comment]
Just had a quick view at the code. Looking go so far - exactly what I was thinking of. The only thing left is to have a brief description of this in the documentation.

**Comment by asibross** [comment]
@joshiste, I added to requested description to the docs.

**Comment by asibross** [comment]
Hey @joshiste, you plan on merging this, or does it need extra work?

**Comment by joshiste** [comment]
Looking good so far, I nee to take a closer look for merging, but currently my time is too limited.

**Comment by joshiste** [comment]
merged with 25373f532425e38857d2ec9a7f16ef528e422f96 and polished with 92a76b1c4ccc46e5b9116a59890c170c890d9744

**Pull request closed without merging**
