### PR TITLE
Upgrade to spring boot 2.7.0 and spring cloud 2021.0.3

### PR DESCRIPTION
**Pull request by antechrestos**
See spring boot 2.7 [release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes) and spring cloud 2021.0.3 [release note](https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2021.0-Release-Notes)

The main points of contributions are the following

* adding `AutoConfiguration` annotation on auto configuration classes. Inner classes keeps their `Configuration`classes as specified in the [documlentation](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#new-autoconfiguration-annotation)
* Removing references to deprecated actuator classe and migrate to `ApiVersion` as specified in former [classe](https://github.com/spring-projects/spring-boot/blob/2.6.x/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/endpoint/http/ActuatorMediaType.java)
* Upgrade hazelcast test to the new hazelcast version

### CODE REVIEW

**Review by erikpetzold — APPROVED** [review]

**Comment by ulischulte** [comment]
@antechrestos,
thanks for the contribution!

**Comment by antechrestos** [comment]
@ulischulte Is a released planned? Thanks and njoy your week-end.

**Comment by ulischulte** [comment]
@antechrestos,
we'll release very soon - no later than friday, I guess.

**Comment by antechrestos** [comment]
@ulischulte Great!

**Pull request merged**
