### PR TITLE
Support CloudFoundry

### PR DESCRIPTION
**Pull request by tetsushiawano**
This PR solve the issue of #434 

### Detail

1. Set HttpHeader X-CF-APP-INSTANCE.

  In the case of spring-boot-admin-client to send metadata of cf_application_guid and cf_instance_index, SBA will check the health status of each instance by setting the HttpHeader X-CF-APP-INSTANCE: "{cf_application_guid}_{cf_instance_index}". 

2. Generate HashedId for each CloudFoundry Instance.

  Now, SBA generates unique HashedId based on the spring-boot-admin-client healthUrl. But CloudFoundry will have the same healthUrl for each instance of the same application. So in the case of a CloudFoundry instance, I add logic to generate a unique HashedId based on "{cf_application_guid}_{cf_instance_index}".

[DEMO running on CF environment](https://spring-boot-admin.cfapps.io/#/applications)

### Others

1. Setting required for CloudFoundry instances.
https://github.com/tetsushiawano/spring-boot-admin-client-app/blob/master/src/main/resources/application.yml#L5-L7

2. Apps used for testing.
https://github.com/tetsushiawano/spring-boot-admin-app
https://github.com/tetsushiawano/spring-boot-admin-client-app

### CODE REVIEW

**Comment by tetsushiawano** [comment]
Got it! I will come back with the change.

**Comment by shakuzen** [comment]
@joshiste 
> Please write a dedicated `CloudFoundryInstanceIdGenerator` and a dedicated `CloudFoundryHttpHeaderProvider` without modyfing the existing implementations.
The `CloudFoundry-*` implementations should be instantiated via AutoConfiguration detecting that the server is running on cloudfoundry.

I initially thought the same thing, but the need for these Cloud Foundry-aware variants is actually dependent on the Spring Boot Admin *client's* platform, not the *server's* platform. In many organizations, this could be expected (assumed?) to always be the same, but not in all. Alternatively, **all clients** may not be running on Cloud Foundry - this is actually true of my organization's current situation. Furthermore, these variants (as they are implemented now) do not negatively affect the behavior of clients that are not on Cloud Foundry, since those clients won't send the Cloud Foundry-specific metadata. Though, of course, I agree this should be demonstrated in tests.

Would you still prefer separate classes given the above?

**Comment by joshiste** [comment]
>Would you still prefer separate classes given the above?

I'd still prefer different classes to separate concerns.  For hybrid environments we could instantiate them always. For the HeaderProvider this should be no problem. 
Also we could just use the app_guid + ":" + index without doing the hashing for CF instances...

Addiotionally It would be nice if spring-boot-admin-clients would automatically add the metadata when running on CF. (may be this needs the concept for a `MetadataContributor` in the client project...

**Comment by tetsushiawano** [comment]
@joshiste @shakuzen 
  I will create the new class as mentioned by @joshiste which can be used for hybrid environments. So whoever want to use the hybrid environment can specify it by overriding the AutoConfiguration. Also, I will use app_guid + ":" + index as unique id of cf instances. Also docs and tests.
  CF instances have VCAP_APPLICATION environment variable which can be used to detect that it is running on CF. And if so it will set the metadata automatically. But then, I feel it would be more consistent if the spring-boot-admin-server can instantiate with the hybrid version from the start. 
  Do you know if there is a method to instantiate with the hybrid one on runtime when detecting there is access from CF?

**Comment by joshiste** [comment]
> Do you know if there is a method to instantiate with the hybrid one on runtime when detecting there is access from CF?

do you mean `@ConditionalOnCloudPlatform(CloudPlatform.CLOUD_FOUNDRY)`?

**Comment by tetsushiawano** [comment]
We can also use this to detect whether running on CF in the spring-boot-admin-client. 
But what I meant was for spring-boot-admin-server where by default it will  instantiate with BasicAuthHttpHeaderProvider and HashingInstanceUrlIdGenerator which does not support CF. I was wondering whether we can re-instantiate with the CloudFoundryInstanceIdGenerator and CloudFoundryHttpHeaderProvider once detecting there is instances running on CF. 
I am talking based on the current plan of creating a new class for the hybrid version.

**Comment by tetsushiawano** [comment]
I add hybrid version class for spring-boot-amin-server in the following branch firstly. 

https://github.com/tetsushiawano/spring-boot-admin/tree/feature/support_cf_v2?files=1 

But I am not sure how to conditionally replace the autoconfiguration. Do I need to create a new autoconfiguration class for the hybrid version or can I modify the existing autoconfiguration class. 

I would like someone's advice.

**Comment by joshiste** [comment]
> I would like someone's advice.

* I'd rather use composition and not inheritance for the `CloudFoundryInstanceIdGenerator`. This allows to alter the fallback IdGenerator easily.

* The CloudFoundryHttpHeaderProvider must extend the BasicAuthHttpHeaderProvider. I just pushed a commit that allows multiple HttpHeadersProviders.

> But I am not sure how to conditionally replace the autoconfiguration. Do I need to create a new autoconfiguration class for the hybrid version or can I modify the existing autoconfiguration class.

I'd prefer to have it in a seperate AutoConfiguration as this allows it to easily disable it

**Comment by tetsushiawano** [comment]
Thanks! I will revise it.

**Comment by tetsushiawano** [comment]
I am the midst of revising but let me post the progress.
https://github.com/codecentric/spring-boot-admin/compare/master...tetsushiawano:feature/support_cf_v2

I am trying to figure out why AdminServerCloudFoundryAutoConfiguration is not run before AdminServerAutoConfiguration. Even though, I put @AutoConfigureBefore({AdminServerAutoConfiguration.class})
https://github.com/codecentric/spring-boot-admin/compare/master...tetsushiawano:feature/support_cf_v2#diff-85c5698c4e623cb8aaf08ca79ded3eeeR31

I upload the latest change to cf but it only shows 1 instance (actually there is 2 instance running) because AdminServerCloudFoundryAutoConfiguration is not run before AdminServerAutoConfiguration.

I will continue tomorrow.

**Comment by joshiste** [comment]
> I am trying to figure out why AdminServerCloudFoundryAutoConfiguration is not run before AdminServerAutoConfiguration. 

I guess it's not run at all. Did you add an entry to the [spring.factories](I am trying to figure out why AdminServerCloudFoundryAutoConfiguration is not run before AdminServerAutoConfiguration. )?

**Comment by tetsushiawano** [comment]
it's not run at all and I didn't set in spring.factories. Thank you for mentioning it! Will revise it today.

**Comment by tetsushiawano** [comment]
@joshiste , Thanks! Now spring-boot-admin-server is working. 
http://spring-boot-admin.cfapps.io/#/applications

I will next proceed implementation of spring-boot-admin-client.

**Comment by tetsushiawano** [comment]
hmm... read `spring-boot-admin-client` but struggling to decide how to fix it. I will consider `MetadataContributor` tomorrow.

**Comment by shakuzen** [comment]
You can add those values to the environment in an `EnvironmentPostProcessor` that is conditionally registered when CloudFoundry is detected.

**Comment by tetsushiawano** [comment]
I will try it. Thanks for advice!

**Comment by joshiste** [comment]
@tetsushiawano the [DiscoveryClient for Cloudfoundry](https://github.com/spring-cloud/spring-cloud-cloudfoundry/blob/master/spring-cloud-cloudfoundry-discovery/src/main/java/org/springframework/cloud/cloudfoundry/discovery/CloudFoundryDiscoveryClient.java) uses the `applicationId` and `instanceId` as metadata-keys. It would useful to use the same keys so we can support users not using the SBA client on CF as well.

**Comment by tetsushiawano** [comment]
Thanks! I will use `applicationId` and `instanceId` as metadata.

**Comment by tetsushiawano** [comment]
I added the EnvironmentPostProcessor but raise the following error.
```
10:56:19.535 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.IllegalArgumentException: Unable to instantiate factory class: org.springframework.boot.env.EnvironmentPostProcessor
	at org.springframework.core.io.support.SpringFactoriesLoader.instantiateFactory(SpringFactoriesLoader.java:161)
	at org.springframework.core.io.support.SpringFactoriesLoader.loadFactories(SpringFactoriesLoader.java:101)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.loadPostProcessors(ConfigFileApplicationListener.java:181)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEnvironmentPreparedEvent(ConfigFileApplicationListener.java:171)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEvent(ConfigFileApplicationListener.java:161)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:74)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:351)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:317)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1234)
	at awano.tetsushi.springbootadminclientapp.SpringBootAdminClientAppApplication.main(SpringBootAdminClientAppApplication.java:10)
Caused by: java.lang.ClassNotFoundException: de.codecentric.boot.admin.client.CloudFoundryEnvironmentPostProcessor
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:264)
	at org.springframework.core.io.support.SpringFactoriesLoader.instantiateFactory(SpringFactoriesLoader.java:153)
	... 15 common frames omitted

Process finished with exit code 1
```
now investigating...

**Comment by tetsushiawano** [comment]
solved.

**Comment by tetsushiawano** [comment]
I'm now struggling to understand why the value is not passed to the following with `@Value`.
https://github.com/tetsushiawano/spring-boot-admin/blob/feature/support_cf_v2/spring-boot-admin-client/src/main/java/de/codecentric/boot/admin/client/config/CloudFoundryEnvironmentPostProcessor.java#L34-L41

**Comment by VincSch** [comment]
Maybe you can have a look at https://github.com/codecentric/spring-boot-admin/issues/434#issuecomment-368297146

**Comment by tetsushiawano** [comment]
@vincsch thank you for sharing! We also did a similar fix first. our method was replacing the core code by creating a customized autoconfiguration. 

I think supporting cloudfoundry out of the box would be beneficial for many people so let me proceed it although struggling at the moment with the client side implementation. 

Also, It would be great if someone could help me with the client side implementation. I'm normally coding Ruby and don't have much experience with Springboot. :)

**Comment by joshiste** [comment]
> I'm normally coding Ruby and don't have much experience with Springboot

Kudos to for trying nonetheless and for contributing

**Comment by shakuzen** [comment]
@joshiste 
> may be this needs the concept for a MetadataContributor in the client project...

It does seem a `MetadataContributor` concept would be helpful for the client-side implementation. Using an `EnvironmentPostProcessor` or just injecting and mutating the metadata in a `@Configuration` class feels like more of a workaround.

**Comment by tetsushiawano** [comment]
I see. Is there document somewhere related to the MetadataContributor concept?

**Comment by joshiste** [comment]
@tetsushiawano I've just pushed the MetadataContributor to master. You just need to implement the interface and add it as bean.

**Comment by tetsushiawano** [comment]
Thank you!

**Comment by tetsushiawano** [comment]
@joshiste I looked at the master branch but couldn't find MetadataContributer. Am I looking at the wrong location? https://github.com/codecentric/spring-boot-admin/commits/master

**Comment by joshiste** [comment]
oops sorry. pushed the wrong branch. It's now here https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-client/src/main/java/de/codecentric/boot/admin/client/registration/metadata/MetadataContributor.java

**Comment by tetsushiawano** [comment]
thanks!

**Comment by tetsushiawano** [comment]
I was able to append metadata automatically by running on CF.
http://spring-boot-admin.cfapps.io/#/applications

Although, I find 2 problems.
(1) `metadata.auto-deregistration`'s value can only be set as String type (needs to be boolean) so it does not work when shutting down 1 CF instance. (still remain to be registered with health status is down.)
(2) I still need to keep `service-base-url` in application.yml as follows. I could not think of good way to override InstanceProperties as modifying DefaultApplicationFactory as it seemed like a dirty fix.
https://github.com/tetsushiawano/spring-boot-admin-client-app/blob/master/src/main/resources/application.yml#L8

@joshiste 
regarding (1), To solve the issue, What do you think of the idea to change metadata type from `Map<String, String>` to `Map<String, Object>`? 
regarding (2), Do you have good idea how to set different `service-base-url` for CF case? 

To solve (1) and (2),
I thought maybe it would be better to use PostProcesserEnvironment instead of MetadataContributor because I can specify properties regarding of the data and its types. I will once try it out tomorrow.

Thank you for support!

**Comment by joshiste** [comment]
ad 1) Having `service-base-url` and `auto-deregistration` in the **metadata** has no effect...
Also as the `DiscoveryClient`'s metadata is `Map<String, String>` I'd like to keep it this way.

ad 2) Basically you want to have different defaults for `spring.boot.admin.client.server-base-url` and `auto-deregistration`?

**Comment by tetsushiawano** [comment]
Got it about `metadata` data type. 

I come to realize yesterday that some properties does not have any effect being on `metadata`. 


Yes, If possible I want to set `spring.boot.admin.client.server-base-url` because CF requires a specific baseUrl to access to the specific CF instance. 

Also, `spring.boot.admin.auto-deregistration` would better be registered as true because CF is not a permanent environment. Instance can be created and destroyed and would result in showing down status for some of the instances. 

I can also set the above 2 properties in each application as well but then spring-boot-admin would not work out of the box. Maybe, let that be and write in the documentation that the 2 properties should be set in each application.

**Comment by tetsushiawano** [comment]
Sorry for taking a long time. 
I finally managed to set the 4 properties automatically in spring-boot-admin-client and confirmed that all of them is working.

4 properties.
https://github.com/tetsushiawano/spring-boot-admin-client-app/blob/master/src/main/resources/application.yml#L6-L9

Below is the demo url.
http://spring-boot-admin.cfapps.io/#/applications

Below is the modified branch.
https://github.com/codecentric/spring-boot-admin/compare/master...tetsushiawano:feature/support_cf_v2?expand=1

Although, 3 tests have error after this fix. I will investigate the cause and fix it tomorrow.
Also, I will add test codes for this modification tomorrow.
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running de.codecentric.boot.admin.client.ClientReactiveApplicationTest
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 9.677 s <<< FAILURE! - in de.codecentric.boot.admin.client.ClientReactiveApplicationTest
[ERROR] test_context(de.codecentric.boot.admin.client.ClientReactiveApplicationTest)  Time elapsed: 8.119 s  <<< ERROR!
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'abstractClientApplicationTest.TestClientApplication': Unsatisfied dependency expressed through field 'registrator'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'registrator' defined in class path resource [de/codecentric/boot/admin/client/config/SpringBootAdminClientAutoConfiguration.class]: Unsatisfied dependency expressed through method 'registrator' parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'applicationFactory' defined in class path resource [de/codecentric/boot/admin/client/config/SpringBootAdminClientAutoConfiguration$ReactiveConfiguration.class]: Unsatisfied dependency expressed through method 'applicationFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'instanceProperties': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'vcap.application.uris[0]' in value "http://${vcap.application.uris[0]}"
	at de.codecentric.boot.admin.client.ClientReactiveApplicationTest.setUp(ClientReactiveApplicationTest.java:35)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'registrator' defined in class path resource [de/codecentric/boot/admin/client/config/SpringBootAdminClientAutoConfiguration.class]: Unsatisfied dependency expressed through method 'registrator' parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'applicationFactory' defined in class path resource [de/codecentric/boot/admin/client/config/SpringBootAdminClientAutoConfiguration$ReactiveConfiguration.class]: Unsatisfied dependency expressed through method 'applicationFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'instanceProperties': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'vcap.application.uris[0]' in value "http://${vcap.application.uris[0]}"
	at de.codecentric.boot.admin.client.ClientReactiveApplicationTest.setUp(ClientReactiveApplicationTest.java:35)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'applicationFactory' defined in class path resource [de/codecentric/boot/admin/client/config/SpringBootAdminClientAutoConfiguration$ReactiveConfiguration.class]: Unsatisfied dependency expressed through method 'applicationFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'instanceProperties': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'vcap.application.uris[0]' in value "http://${vcap.application.uris[0]}"
	at de.codecentric.boot.admin.client.ClientReactiveApplicationTest.setUp(ClientReactiveApplicationTest.java:35)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'instanceProperties': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'vcap.application.uris[0]' in value "http://${vcap.application.uris[0]}"
	at de.codecentric.boot.admin.client.ClientReactiveApplicationTest.setUp(ClientReactiveApplicationTest.java:35)
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'vcap.application.uris[0]' in value "http://${vcap.application.uris[0]}"
	at de.codecentric.boot.admin.client.ClientReactiveApplicationTest.setUp(ClientReactiveApplicationTest.java:35)

[ERROR] test_context(de.codecentric.boot.admin.client.ClientReactiveApplicationTest)  Time elapsed: 8.12 s  <<< ERROR!
java.lang.NullPointerException
	at de.codecentric.boot.admin.client.ClientReactiveApplicationTest.shutdown(ClientReactiveApplicationTest.java:42)

[INFO] Running de.codecentric.boot.admin.client.ClientServletApplicationTest
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 3.337 s <<< FAILURE! - in de.codecentric.boot.admin.client.ClientServletApplicationTest
[ERROR] test_context(de.codecentric.boot.admin.client.ClientServletApplicationTest)  Time elapsed: 3.336 s  <<< ERROR!
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'abstractClientApplicationTest.TestClientApplication': Unsatisfied dependency expressed through field 'registrator'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'registrator' defined in class path resource [de/codecentric/boot/admin/client/config/SpringBootAdminClientAutoConfiguration.class]: Unsatisfied dependency expressed through method 'registrator' parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'applicationFactory' defined in class path resource [de/codecentric/boot/admin/client/config/SpringBootAdminClientAutoConfiguration$ServletConfiguration.class]: Unsatisfied dependency expressed through method 'applicationFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'instanceProperties': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'vcap.application.uris[0]' in value "http://${vcap.application.uris[0]}"
	at de.codecentric.boot.admin.client.ClientServletApplicationTest.setUp(ClientServletApplicationTest.java:35)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'registrator' defined in class path resource [de/codecentric/boot/admin/client/config/SpringBootAdminClientAutoConfiguration.class]: Unsatisfied dependency expressed through method 'registrator' parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'applicationFactory' defined in class path resource [de/codecentric/boot/admin/client/config/SpringBootAdminClientAutoConfiguration$ServletConfiguration.class]: Unsatisfied dependency expressed through method 'applicationFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'instanceProperties': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'vcap.application.uris[0]' in value "http://${vcap.application.uris[0]}"
	at de.codecentric.boot.admin.client.ClientServletApplicationTest.setUp(ClientServletApplicationTest.java:35)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'applicationFactory' defined in class path resource [de/codecentric/boot/admin/client/config/SpringBootAdminClientAutoConfiguration$ServletConfiguration.class]: Unsatisfied dependency expressed through method 'applicationFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'instanceProperties': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'vcap.application.uris[0]' in value "http://${vcap.application.uris[0]}"
	at de.codecentric.boot.admin.client.ClientServletApplicationTest.setUp(ClientServletApplicationTest.java:35)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'instanceProperties': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'vcap.application.uris[0]' in value "http://${vcap.application.uris[0]}"
	at de.codecentric.boot.admin.client.ClientServletApplicationTest.setUp(ClientServletApplicationTest.java:35)
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'vcap.application.uris[0]' in value "http://${vcap.application.uris[0]}"
	at de.codecentric.boot.admin.client.ClientServletApplicationTest.setUp(ClientServletApplicationTest.java:35)

[ERROR] test_context(de.codecentric.boot.admin.client.ClientServletApplicationTest)  Time elapsed: 3.336 s  <<< ERROR!
java.lang.NullPointerException
	at de.codecentric.boot.admin.client.ClientServletApplicationTest.shutdown(ClientServletApplicationTest.java:42)

[INFO] Running de.codecentric.boot.admin.client.config.SpringBootAdminClientAutoConfigurationTest
[ERROR] Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 8.836 s <<< FAILURE! - in de.codecentric.boot.admin.client.config.SpringBootAdminClientAutoConfigurationTest
[ERROR] active(de.codecentric.boot.admin.client.config.SpringBootAdminClientAutoConfigurationTest)  Time elapsed: 1.75 s  <<< ERROR!
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cloudFoundryMetadataContributor': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'vcap.application.application_id' in value "${vcap.application.application_id}"
	at de.codecentric.boot.admin.client.config.SpringBootAdminClientAutoConfigurationTest.load(SpringBootAdminClientAutoConfigurationTest.java:70)
	at de.codecentric.boot.admin.client.config.SpringBootAdminClientAutoConfigurationTest.active(SpringBootAdminClientAutoConfigurationTest.java:49)
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'vcap.application.application_id' in value "${vcap.application.application_id}"
	at de.codecentric.boot.admin.client.config.SpringBootAdminClientAutoConfigurationTest.load(SpringBootAdminClientAutoConfigurationTest.java:70)
	at de.codecentric.boot.admin.client.config.SpringBootAdminClientAutoConfigurationTest.active(SpringBootAdminClientAutoConfigurationTest.java:49)
```

**Comment by tetsushiawano** [comment]
I created another PR so it is ok to close this PR. Sorry, I don't know how to close the PR so I would like someone to close this. thanks!

**Comment by joshiste** [comment]
closed in favor of #655

**Pull request closed without merging**
