### PR TITLE
Added HTTPS/SSL Support

### PR DESCRIPTION
**Pull request by steve-oakey**
I had the requirement to use with application with SSL Client Authentication.
The SimpleHostRoutingFilter was not able to provide this, nor was
it extensible to allow a proper subclass. I provided an implementation
which uses most aspects of SimpleHostRoutingFilter, but builds the
HTTP client using current API as well as building a correct SSLContext
based on the javax.net.ssl JVM properties.

The client auto-configuration now provides a RestTemplate bean that builds
an SSLContext if SSL is enabled for the client application. If not, the 
original RestTemplate is used.

A modification was needed to the AdminClientProperties to determine if
the connection requires https instead of http (checks ServerProperties
for an instance of Ssl).

I also added spring-configuration-processor as a dependency as to generate
property file metadata.

### CODE REVIEW

**Comment by steve-oakey** [comment]
I will address the drop in test coverage tomorrow evening.

**Comment by joshiste** [comment]
The autodetection of https on client is a goog idea.
But I think the  changes to the resttemplate and securehostroutingfilter aren't necessary. Did you have a look at #66?

**Comment by steve-oakey** [comment]
Sorry, I did not. I will re-investigate tonight. I will revert those
changes and see if the issues I was having still occur.

It would be great if the SecureHostRoutingFilter was not necessary, but I
thought the custom SSLSocketFactory in the class was not not loading the
trust information correctly. As well it uses the
'AllowAllHostnameVerifier'  with the connection manager. If the client
requires x509 authentication via Spring Security (as well as the server) I
don't think it will work with just the JVM properties alone.

I will look at this tonight. Thank you for your comments and consideration.

**Comment by steve-oakey** [comment]
You were correct about not needing a new RestTemplate. Adding the java.net.ssl JVM properties was enough for the client application to ping the server successfully with x509 client authentication.

However the server cannot complete the requests back to the client using the [SimpleHostRoutingFilter](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/route/SimpleHostRoutingFilter.java). It does not build the HTTP client with an SSLContext that can make a secure connection back to the client. It uses a custom SSLSocket which (appears) not to load the key or trust store information. This may be an issue I can bring up with the spring-cloud-netflix project.

Shall I close this pull request? I can maintain a fork and use it until Spring Cloud can update that class, but as it stands now it will not work when the client requires x509 authentication.

**Comment by joshiste** [comment]
I'd bee keen to do the changes to AdminClientProperties.
And the SecureHostRoutingFilter should be addressed in https://github.com/spring-cloud/spring-cloud-netflix

**Comment by steve-oakey** [comment]
Sounds good. I will submit a new pull request as not to pollute the commit
history. This one can be closed.

-Steve

**Comment by joshiste** [comment]
Just git reset to codecentric/master do your changes and force push 'em.
The PR will be updated.  No need for a new one
Am 03.05.2015 22:21 schrieb "Steve Oakey" <notifications@github.com>:

**Comment by steve-oakey** [comment]
Done, updated with test case. Thanks.

**Comment by joshiste** [comment]
Merged your commit. Thanks!
I divided the configuration-annotation-processor into a second commit and added descriptions to the properties.

**Comment by steve-oakey** [comment]
Great, thanks!

- Steve

**Pull request closed without merging**
