### PR TITLE
fix: Compatibility with Spring Boot Admin 1.5.x client status updates

### PR DESCRIPTION
**Pull request by huangguangshan**
When using Spring Boot version 1.5.X as a client to connect to a Spring Boot Admin 2.7.X server, the logs continuously show 'Couldn't retrieve info for XXXX.' 
This is because the 'InfoUpdater#convertInfo()' method checks 'isApiMediaType' using 'org.springframework.boot.actuate.endpoint.ApiVersion' for version comparison. The 2.7.X server's actuator version only has V2 and V3, which results in the 1.X client registration and status update continuously logging 'Couldn't retrieve info for XX'.

### CODE REVIEW

**Comment by ulischulte** [comment]
Hi @huangguangshan,

thanks for contributing, we'll have a look at this. First of all, I would advise you not to mix up versions of clients and SBA server. They should always share the same version. You can simply change the version inside your client application and everything should just be fine.

Regards,
Uli

**Comment by erikpetzold** [comment]
@ulischulte I think that's not correct, the sba client version should match the Spring Boot Version of the app (major+minor)

**Comment by huangguangshan** [comment]
> @ulischulte I think that's not correct, the sba client version should match the Spring Boot Version of the app (major+minor)

i

> Hi @huangguangshan,
> 
> thanks for contributing, we'll have a look at this. First of all, I would advise you not to mix up versions of clients and SBA server. They should always share the same version. You can simply change the version inside your client application and everything should just be fine.
> 
> Regards, Uli

I'm pleased to receive your response, but our current client project is using Spring Boot 1.5.X, so it can't be changed to align with the server's version. Furthermore, Chapter 7 of the Spring Boot Admin documentation also states that it supports client versions 1.5.X. Here's the link: https://docs.spring-boot-admin.com/2.7.2/#monitoring-spring-boot-1.5.x

**Comment by ulischulte** [comment]
@erikpetzold,
you're perfectly right.
But still, I wouldn't favor backward compatibility with each and every Spring Boot version over sacrificing maintainability.
The MediaType `vnd.spring-boot.actuator.v1+json` is not supported by Spring Boot 2.7.x and has been removed with version 2.2.0. We might run into side effects by just accepting it.
Imho, it's still better to stick to the latest compatible SBA server version if you can't upgrade your clients.

**Comment by SteKoe** [comment]
Hi,

just to add my 5 cents: Whenever we call a service (i.e. Spring Boot 1.5.X) that returns a "legacy" response, we convert the response (including the headers) to fit a format that we require. A legacy response is defined as V1_ACTUATOR_JSON or simple JSON response type (see https://github.com/codecentric/spring-boot-admin/blob/2.7.x/spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/web/client/InstanceExchangeFilterFunctions.java#L136). 

Whenever we identify a response as "legacy" we replace headers to the latest ApiVersion provided by Spring Boot (see https://github.com/codecentric/spring-boot-admin/blob/2.7.x/spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/web/client/InstanceExchangeFilterFunctions.java#L144) and apply a transform function (see https://github.com/codecentric/spring-boot-admin/blob/2.7.x/spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/web/client/LegacyEndpointConverters.java#L118).

Hence,  a V1_ACTUATOR_JSON response never hits InfoUpdater and ApiMediaTypeHandler at all, but will be transformed to V3_ACTUATOR_JSON before. Therefor I assume that you have a different issue in your setup which causes Spring Boot Admin not be able to retrieve info updates. 

I have set up a Spring Boot Admin 2.7.4 and a simple Spring Boot service using Spring Boot 1.5.20.RELEASE. The application.properties file of the monitored service looks as follows:

```properties
app.spring.boot.version="@project.version@"
management.security.enabled=false
spring.boot.admin.api-path=instances
spring.boot.admin.url=http://localhost:8080
server.port=8081
```

Using this setup, calling the info endpoint works like a charm. That leads me to several questions:

1. Do you override beans of Spring Boot Admin that might change the behavior?
2. Is any call (e.g. health check) working as expected?
3. Is the info endpoint available when you call it directly via curl or similar?
4. Can you provide us an example project that reproduces the issue?

Thank you!

**Comment by huangguangshan** [comment]
> 你好，
> 
> 只是补充我的 5 美分：每当我们调用返回“旧版”响应的服务（即 Spring Boot 1.5.X）时，我们都会将响应（包括标头）转换为适合我们需要的格式。旧响应定义为 V1_ACTUATOR_JSON 或简单 JSON 响应类型（请参阅[https://github.com/codecentric/spring-boot-admin/blob/2.7.x/spring-boot-admin-server/src/main/java/ de/codecentric/boot/admin/server/web/client/InstanceExchangeFilterFunctions.java#L136](https://github.com/codecentric/spring-boot-admin/blob/2.7.x/spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/web/client/InstanceExchangeFilterFunctions.java#L136)）。
> 
> 每当我们将响应识别为“旧版”时，我们都会将标头替换为 Spring Boot 提供的最新 ApiVersion（请参阅[https://github.com/codecentric/spring-boot-admin/blob/2.7.x/spring-boot-admin- server/src/main/java/de/codecentric/boot/admin/server/web/client/InstanceExchangeFilterFunctions.java#L144](https://github.com/codecentric/spring-boot-admin/blob/2.7.x/spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/web/client/InstanceExchangeFilterFunctions.java#L144)）并应用转换函数（请参阅[https://github.com/codecentric/spring-boot-admin /blob/2.7.x/spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/web/client/LegacyEndpointConverters.java#L118](https://github.com/codecentric/spring-boot-admin/blob/2.7.x/spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/web/client/LegacyEndpointConverters.java#L118)）。
> 
> 因此，V1_ACTUATOR_JSON 响应根本不会命中 InfoUpdater 和 ApiMediaTypeHandler，但之前会转换为 V3_ACTUATOR_JSON。因此，我假设您的设置中存在不同的问题，导致 Spring Boot Admin 无法检索信息更新。
> 
> 我已经使用 Spring Boot 1.5.20.RELEASE 设置了 Spring Boot Admin 2.7.4 和简单的 Spring Boot 服务。受监控服务的application.properties文件如下所示：
> 
> ```ini
> app.spring.boot.version="@project.version@"
> management.security.enabled=false
> spring.boot.admin.api-path=instances
> spring.boot.admin.url=http://localhost:8080
> server.port=8081
> ```
> 
> 使用此设置，调用信息端点就像一个魅力。这让我想到几个问题：
> 
> 1. 您是否覆盖了可能会改变行为的 Spring Boot Admin 的 beans？
> 2. 任何呼叫（例如健康检查）是否按预期工作？
> 3. 当您直接通过curl或类似方式调用它时，信息端点是否可用？
> 4. 您能为我们提供一个重现该问题的示例项目吗？
> 
> 谢谢你！



> Hi,
> 
> just to add my 5 cents: Whenever we call a service (i.e. Spring Boot 1.5.X) that returns a "legacy" response, we convert the response (including the headers) to fit a format that we require. A legacy response is defined as V1_ACTUATOR_JSON or simple JSON response type (see https://github.com/codecentric/spring-boot-admin/blob/2.7.x/spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/web/client/InstanceExchangeFilterFunctions.java#L136).
> 
> Whenever we identify a response as "legacy" we replace headers to the latest ApiVersion provided by Spring Boot (see https://github.com/codecentric/spring-boot-admin/blob/2.7.x/spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/web/client/InstanceExchangeFilterFunctions.java#L144) and apply a transform function (see https://github.com/codecentric/spring-boot-admin/blob/2.7.x/spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/web/client/LegacyEndpointConverters.java#L118).
> 
> Hence, a V1_ACTUATOR_JSON response never hits InfoUpdater and ApiMediaTypeHandler at all, but will be transformed to V3_ACTUATOR_JSON before. Therefor I assume that you have a different issue in your setup which causes Spring Boot Admin not be able to retrieve info updates.
> 
> I have set up a Spring Boot Admin 2.7.4 and a simple Spring Boot service using Spring Boot 1.5.20.RELEASE. The application.properties file of the monitored service looks as follows:
> 
> ```ini
> app.spring.boot.version="@project.version@"
> management.security.enabled=false
> spring.boot.admin.api-path=instances
> spring.boot.admin.url=http://localhost:8080
> server.port=8081
> ```
> 
> Using this setup, calling the info endpoint works like a charm. That leads me to several questions:
> 
> 1. Do you override beans of Spring Boot Admin that might change the behavior?
> 2. Is any call (e.g. health check) working as expected?
> 3. Is the info endpoint available when you call it directly via curl or similar?
> 4. Can you provide us an example project that reproduces the issue?
> 
> Thank you!

In response, thank you for your reply. It has helped me pinpoint the issue more clearly. The problem lies in the configuration of my server-side project, which resulted in 'legacyEndpointConverterInstanceExchangeFilter' not being loaded.

**Comment by SteKoe** [comment]
Thanks for reporting back and closing the PR :) We are happy to help and glad that you found a solution!

**Pull request closed without merging**
